### ISSUE TITLE
First two values read by load_from_txt and load when using a .csv are always wrong (random)

### ISSUE THREAD

**Issue by Andrea-Oliveri** [deephealthproject/eddl#111]
Good Morning,
the `load_from_txt` and `load` functions do not work correctly when used on a .csv file (not tested on other types of files).
Proof of concept in zip (simply load and print tensor).
I also invite you to type `cat -A test.csv` to see that the file does not contain any hidden characters.

[test.zip](https://github.com/deephealthproject/eddl/files/4297286/test.zip)

**Comment by CostantinoGrana** [comment]
Confirmed. 

The bug is here: https://github.com/deephealthproject/eddl/blob/2f09f9237c9f2d6cd626f7de9c096065c8c4b061/src/tensor/tensor_serialization.cpp#L167

This is due to the fact that the pointer passed to this constructor:
`Tensor(const vector<int> &shape, float *fptr, int dev=DEV_CPU);`
is directly used by the Tensor (ownership is transferred). But the data is coming from a vector, which still owns that data. That data needs to be copied, since `Tensor`s assume ownership (it deletes the pointer in the destructor).

Upon correcting the bug, the documentation should make it clear that the constructor requires taking ownership of the pointer.

**Comment by salvacarrion** [comment]
Thank you! I fix it in a moment

**Comment by salvacarrion** [comment]
Done. I've pushed it to master. Can you confirm if the fix works? 
Ps.: I've also updated the tests

**Comment by Andrea-Oliveri** [comment]
I confirm the issue seems to be solved. Thank you very much!
